# Site settings

title: 小强
SEOTitle: 窗外蟋蟀的博客 | Keysaim Blog
header-img: img/home-bg-hill.jpg
email: keysaim@gmail.com
description: "描述"
keyword: "窗外蟋蟀, keysaim"
url: "https://weiwangqiang.github.io"
baseurl: ""

# Sidebar 
settings
sidebar: true   # 是否开启侧边栏.

sidebar-about-description: "不装逼"

sidebar-avatar:/img/me.png     

# SNS settings
RSS: false
zhihu_username:     小强
github_username:    weiwangqiang

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页


friends: [
    {
        title: "csdn blog",
        href: "https://blog.csdn.net/to_perfect"
    },{
        title: "android",
        href: "https://developer.android.google.cn/"
    }
]
...